name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is cloned

      - name: List repository contents (debug)
        run: ls -R /home/runner/work/altitude_landing/altitude-landing

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd altitude-landing
          ls -l  # Confirm package-lock.json is here
          npm ci

      - name: Build with Next.js
        run: |
          cd altitude-landing
          npm run build

      - name: List directory contents after build
        run: ls -R altitude-landing

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./altitude-landing/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
